---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/8/4 15:11
---

OrmDb = {
    tag = "未定义",
}

tableDb = {
    db = {}
}

local meta = {}

function meta:rows()
    print(self.tag)
end

function OrmDb:new(obj)
    obj = obj or {}
    aa = setmetatable(obj, { __index = meta })
    return obj
end

function OrmDb:rows()
end

function OrmDb:log()
    print("log")
end

return OrmDb