---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/5/14 15:49
---
json = require("json")

function test()
    ini = require 'ini'
    settings1 = ini.parse_file("app.ini")
    print("settings1类型：", type(settings1))
    print(json.encode(settings1))
end
test()

