---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/29 13:34
---
chapter3 = {}

function chapter3.show()
    findMax()
    --printWeb()
end

function move1()
    local a = 0
    while (a < 3) do
        printLine("while")
        print(a)
        a = a + 1
    end
    for i = 4, 6 do
        printLine("for")
        print(i)
    end
    repeat
        printLine("repeat")
        print(a)
        a = a + 1
    until (a == 4)
end

function rep2()
    for i = 200, 10, -10
    do
        print(i)

    end
end

function findMax()
    numArray = { 1, 10, 23, 12, 5, 102, 5656, 5, 8 }
    print(addParams(1, 15, 156))
end

function addParams(...)
    pa1 = { 1, 22, 333, 4444; 55555 }
    pa2 = { aa = 1, bb = 22, cc = 333 }
    printLine("多参数")
    for i, v in ipairs { ... } do
        print(i, v)
    end

    printLine("数组")
    for i, v in ipairs(pa1) do
        print(i, v)
    end

    printLine("Map")
    for k, v in pairs(pa2) do
        print(k, v)
    end

    printLine("个数")
    print("多参数=" .. #{ ... })
    print("数组=" .. #pa1)
    print("Map=" .. #pa2)

    printLine("多参数2")
    for i = 1,select('#', ...) do
       local arg= select(i,...)
        print(arg)
    end

end
