---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/29 13:34
---
chapter3 = {}

function chapter3.show()
    rep2()
end

function move1()
    local a = 0
    while (a < 3) do
        printLine("while")
        print(a)
        a = a + 1
    end
    for i = 4, 6 do
        printLine("for")
        print(i)
    end
    repeat
        printLine("repeat")
        print(a)
        a = a + 1
    until (a == 4)
end

function rep2()
    for i = 200, 10, -10
    do
        print(i)

    end
end