---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/28 17:31
---
module = {}

-- 定义一个常量
module.constant = "这是一个常量"

function module.func1()
    io.write("这是一个公有函数！\n")
    io.write("这是一个公有函数！\n")
    io.write("这是一个公有函数！\n")
end

local function func2()
    print("这是一个私有函数！")
end

function module.func3()
    func2()
end

print(module.func3())