---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/6/9 10:30
---

chapter4 = {}

function chapter4.show()
    mi(2)
end

function mi(a)
    print(a ^ 4)
end

function relationship(a, b)
    print(a == b)
end