---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/28 17:31
---
chapter1 = {}

-- 定义一个常量
chapter1.constant = "这是一个常量"

function chapter1.add()
    value = "1" + 1
    return value + 3
end

function chapter1.show()
    function funcName()
        for i = 1, 10 do
            value = factorial1(i)
            print(value)
        end
    end
    funcName()
end

function addString(a, b)
    newString = a .. b
    print(newString)
    print(#a)
end

function nameIt(name)
    print(name)
end

function table()
    local tbl = { "apple", "pear", "orange", "grape" }
    --for key, value in pairs(tbl) do
    --    print("key="..key.." and  value=" .. value)
    --end

    for i = 1, 4 do
        print(tbl[i])
    end
end

function factorial1(n)
    if n == 0 then
        return 1
    else
        return n * factorial1(n - 1)
    end
end


