---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/28 13:40
---

require("user")
require("chapter1")
require("chapter2")
require("chapter3")
require("Utils")
require("chapter4")

print(relationship(10,20))
