---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/28 13:40
---

require("user")
require("chapter1")
require("chapter2")
--user.func1()
--
--print(user.html)

--print(chapter1.show())

print(chapter2.show())