---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wkx.
--- DateTime: 2019/5/29 11:00
---
Utils = {}

function printLine(word)
    if type(word) == "nil" then
        word = "divider"
    end
    print("\n********************" .. word .. "*******************************")
end