---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/5/8 10:17
---
http = require("socket.http")
httpClient = {}

function httpClient.Test()
    --httpRequest()
    post()
end

-- 页面请求
function httpRequest()
    --result = http.request("https://www.baidu.com/")
    --print(result)
end

-- post请求
function post()
    local request_body = [[login=user&password=123]]
    local response_body = {}
    local res, code, response_headers = http.request {
        url = "http://175.24.128.25:8090/api/account/getAllUser",
        method = "POST",
        headers = {
            ["Content-Type"] = "application/x-www-form-urlencoded";
            ["Content-Length"] = #request_body;
        },
        source = ltn12.source.string(request_body),
        sink = ltn12.sink.table(response_body),
    }
    print(res)
    print(code)
    if type(response_headers) == "table" then
        for k, v in pairs(response_headers) do
            print(k, v)
        end
    end
    print("Response body:")
    if type(response_body) == "table" then
        print(#response_body)
        print(table.concat(response_body))
    else
        print("Not a table:", type(response_body))
    end

end

return httpClient
