---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wakfu.
--- DateTime: 2020/5/13 10:37
---

local function _instantiate(class, ...)
    local inst = setmetatable({}, { __index = class })

    if inst.init then
        inst:init(...)
    end
    return inst
end

function class(base)
    return setmetatable({}, {
        __call = _instantiate,
        __index = base
    })
end